[platformio]
src_dir = main


[env:esp32s3-custom]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200


[env:ble_node_baseline]
extends = env:esp32s3-custom
board_build.partitions = partitions.csv
build_flags = 
    ${env:esp32s3-custom.build_flags}
    -DBASELINE_TEST=1