BLE Mesh Multi-Sensor Server: main/board.h File Reference
board.h File Reference
Board-specific LED and GPIO helpers.
#include "driver/gpio.h"
Classes
struct _led_state
LED state tracking structure.
Macros
#define LED_ON 1
#define LED_OFF 0
Functions
void board_led_operation (uint8_t pin, uint8_t onoff)
Turn a board LED on or off.
void board_init (void)
Initialize board peripherals.
Detailed Description
Board-specific LED and GPIO helpers.
Definition in file board.h.
Macro Definition Documentation
LED_OFF
#define LED_OFF 0
Definition at line 59 of file board.h.
Referenced by board_led_init(), and prov_complete().
LED_ON
#define LED_ON 1
< __cplusplus
Definition at line 58 of file board.h.
Referenced by ble_mesh_init().
Function Documentation
board_init()
void board_init (void)
Initialize board peripherals.
__cplusplus
Initialize board peripherals.
Definition at line 62 of file board.c.
References board_led_init().
Referenced by app_main().
board_led_operation()
void board_led_operation (uint8_t pin, uint8_t onoff)
Turn a board LED on or off.
Turn a board LED on or off.
Definition at line 27 of file board.c.
References led_state, _led_state::name, _led_state::pin, _led_state::previous, and TAG.
Referenced by ble_mesh_init(), and prov_complete().