BLE Mesh Multi-Sensor Server: main/board.c File Reference
board.c File Reference
#include <stdio.h>
#include "driver/gpio.h"
#include "esp_log.h"
#include "board.h"
Macros
#define TAG "BOARD"
Functions
void board_led_operation (uint8_t pin, uint8_t onoff)
Set LED GPIO level and track previous state.
static void board_led_init (void)
Initialize LED GPIO pins to output and off state.
void board_init (void)
Initialize board-level hardware.
Variables
struct _led_state led_state [3]
LED state table for RGB indicators.
Macro Definition Documentation
TAG
#define TAG "BOARD"
Definition at line 15 of file board.c.
Referenced by board_led_operation().
Function Documentation
board_init()
void board_init (void)
Initialize board-level hardware.
Initialize board peripherals.
Definition at line 62 of file board.c.
References board_led_init().
Referenced by app_main().
board_led_init()
static void board_led_init (void) static
Initialize LED GPIO pins to output and off state.
Definition at line 49 of file board.c.
References LED_OFF, led_state, _led_state::pin, and _led_state::previous.
Referenced by board_init().
board_led_operation()
void board_led_operation (uint8_t pin, uint8_t onoff)
Set LED GPIO level and track previous state.
Turn a board LED on or off.
Definition at line 27 of file board.c.
References led_state, _led_state::name, _led_state::pin, _led_state::previous, and TAG.
Referenced by ble_mesh_init(), and prov_complete().
Variable Documentation
led_state
struct _led_state led_state[3]
Initial value:
= {
    { LED_OFF, LED_OFF, LED_R, "red"   },
    { LED_OFF, LED_OFF, LED_G, "green" },
    { LED_OFF, LED_OFF, LED_B, "blue"  },
}
LED state table for RGB indicators.
Definition at line 18 of file board.c.
Referenced by board_led_init(), and board_led_operation().