BLE Mesh Multi-Sensor Server: main/main.c File Reference
main.c File Reference
BLE Mesh vendor server with sensor integration and periodic publishing.
#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_timer.h"
#include "esp_ble_mesh_defs.h"
#include "esp_ble_mesh_common_api.h"
#include "esp_ble_mesh_networking_api.h"
#include "esp_ble_mesh_provisioning_api.h"
#include "esp_ble_mesh_config_model_api.h"
#include "esp_bt_device.h"
#include "esp_gap_ble_api.h"
#include "board.h"
#include "ble_mesh_example_init.h"
#include "config.h"
#include "sensors/aht20.h"
#include "sensors/max30101.h"
#include "sensors/SGP30.h"
Macros
#define TAG "MESH_SERVER"
Log tag for this module.
#define CID_ESP 0x02E5
#define ESP_BLE_MESH_VND_MODEL_ID_CLIENT 0x0000
#define ESP_BLE_MESH_VND_MODEL_ID_SERVER 0x0001
#define ESP_BLE_MESH_VND_MODEL_OP_SEND ESP_BLE_MESH_MODEL_OP_3(0x00, CID_ESP)
#define ESP_BLE_MESH_VND_MODEL_OP_STATUS ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
#define OP_SENSOR_STATUS ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
Functions
ESP_BLE_MESH_MODEL_PUB_DEFINE (vnd_pub, 3+18, ROLE_NODE)
static void pub_timer_cb (void *arg)
Sensor data publication callback.
static void prov_complete (uint16_t net_idx, uint16_t addr, uint8_t flags, uint32_t iv_index)
Handle provisioning completion and turn off status LED.
static void example_ble_mesh_provisioning_cb (esp_ble_mesh_prov_cb_event_t event, esp_ble_mesh_prov_cb_param_t *param)
BLE Mesh provisioning callback for node events.
static void example_ble_mesh_config_server_cb (esp_ble_mesh_cfg_server_cb_event_t event, esp_ble_mesh_cfg_server_cb_param_t *param)
Configuration server callback for model state changes.
static void example_ble_mesh_custom_model_cb (esp_ble_mesh_model_cb_event_t event, esp_ble_mesh_model_cb_param_t *param)
Vendor model callback for send/receive events.
static esp_err_t ble_mesh_init (void)
Initialize BLE Mesh stack and provisioning bearers.
void app_main (void)
Application entry point.
Variables
static esp_timer_handle_t pub_timer
static esp_ble_mesh_model_t * s_vnd_model
static uint8_t dev_uuid [ESP_BLE_MESH_OCTET16_LEN] = { 0x32, 0x10 }
static esp_ble_mesh_cfg_srv_t config_server
Configuration Server model state.
static esp_ble_mesh_model_t root_models []
Root model list for the primary element.
static esp_ble_mesh_model_op_t vnd_op []
Vendor model operation table.
static esp_ble_mesh_model_t vnd_models []
Vendor model instances for this node.
static esp_ble_mesh_elem_t elements []
Element list for this composition.
static esp_ble_mesh_comp_t composition
Node composition data.
static esp_ble_mesh_prov_t provision
Provisioning capabilities and identifiers.
Detailed Description
BLE Mesh vendor server with sensor integration and periodic publishing.
Definition in file main.c.
Macro Definition Documentation
CID_ESP
#define CID_ESP 0x02E5
Definition at line 42 of file main.c.
ESP_BLE_MESH_VND_MODEL_ID_CLIENT
#define ESP_BLE_MESH_VND_MODEL_ID_CLIENT 0x0000
Definition at line 43 of file main.c.
ESP_BLE_MESH_VND_MODEL_ID_SERVER
#define ESP_BLE_MESH_VND_MODEL_ID_SERVER 0x0001
Definition at line 44 of file main.c.
ESP_BLE_MESH_VND_MODEL_OP_SEND
#define ESP_BLE_MESH_VND_MODEL_OP_SEND ESP_BLE_MESH_MODEL_OP_3(0x00, CID_ESP)
Definition at line 46 of file main.c.
Referenced by example_ble_mesh_custom_model_cb().
ESP_BLE_MESH_VND_MODEL_OP_STATUS
#define ESP_BLE_MESH_VND_MODEL_OP_STATUS ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
Definition at line 47 of file main.c.
Referenced by example_ble_mesh_custom_model_cb().
OP_SENSOR_STATUS
#define OP_SENSOR_STATUS ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
Definition at line 50 of file main.c.
Referenced by pub_timer_cb().
TAG
#define TAG "MESH_SERVER"
Log tag for this module.
Definition at line 39 of file main.c.
Referenced by app_main(), ble_mesh_init(), example_ble_mesh_config_server_cb(), example_ble_mesh_custom_model_cb(), example_ble_mesh_provisioning_cb(), prov_complete(), and pub_timer_cb().
Function Documentation
app_main()
void app_main (void)
Application entry point.
Definition at line 406 of file main.c.
References aht20_init(), BLE_MESH_DEVICE_NAME, ble_mesh_init(), board_init(), dev_uuid, max30101_init(), max30101_start_sampling(), sgp30_init(), and TAG.
ble_mesh_init()
static esp_err_t ble_mesh_init (void) static
Initialize BLE Mesh stack and provisioning bearers.
Definition at line 369 of file main.c.
References BLE_MESH_DEVICE_NAME, board_led_operation(), composition, example_ble_mesh_config_server_cb(), example_ble_mesh_custom_model_cb(), example_ble_mesh_provisioning_cb(), LED_ON, provision, and TAG.
Referenced by app_main().
ESP_BLE_MESH_MODEL_PUB_DEFINE()
ESP_BLE_MESH_MODEL_PUB_DEFINE (vnd_pub , 3+ 18, ROLE_NODE)
example_ble_mesh_config_server_cb()
static void example_ble_mesh_config_server_cb (esp_ble_mesh_cfg_server_cb_event_t event, esp_ble_mesh_cfg_server_cb_param_t * param) static
Configuration server callback for model state changes.
Definition at line 309 of file main.c.
References TAG.
Referenced by ble_mesh_init().
example_ble_mesh_custom_model_cb()
static void example_ble_mesh_custom_model_cb (esp_ble_mesh_model_cb_event_t event, esp_ble_mesh_model_cb_param_t * param) static
Vendor model callback for send/receive events.
Definition at line 338 of file main.c.
References ESP_BLE_MESH_VND_MODEL_OP_SEND, ESP_BLE_MESH_VND_MODEL_OP_STATUS, TAG, and vnd_models.
Referenced by ble_mesh_init().
example_ble_mesh_provisioning_cb()
static void example_ble_mesh_provisioning_cb (esp_ble_mesh_prov_cb_event_t event, esp_ble_mesh_prov_cb_param_t * param) static
BLE Mesh provisioning callback for node events.
Definition at line 248 of file main.c.
References prov_complete(), pub_timer, pub_timer_cb(), s_vnd_model, TAG, and vnd_models.
Referenced by ble_mesh_init().
prov_complete()
static void prov_complete (uint16_t net_idx, uint16_t addr, uint8_t flags, uint32_t iv_index) static
Handle provisioning completion and turn off status LED.
Definition at line 238 of file main.c.
References board_led_operation(), LED_OFF, and TAG.
Referenced by example_ble_mesh_provisioning_cb().
pub_timer_cb()
static void pub_timer_cb (void * arg) static
Sensor data publication callback.
Called periodically to read sensor data and publish to BLE Mesh network. Payload format (18 bytes): 0-1: temp_x100 (int16 LE) 2-3: rh_x100 (uint16 LE) 4-7: raw RED (uint32 LE) 8-11: raw IR (uint32 LE) 12: heart_rate (uint8) 13: spo2 (uint8) 14-15: eco2 (uint16 LE) 16-17: tvoc (uint16 LE)
Definition at line 157 of file main.c.
References aht20_read_x100(), max30101_get_heart_rate(), max30101_get_raw_values(), max30101_get_spo2(), OP_SENSOR_STATUS, s_vnd_model, and TAG.
Referenced by example_ble_mesh_provisioning_cb().
Variable Documentation
composition
esp_ble_mesh_comp_t composition static
Initial value:
= {
    .cid = CID_ESP,
    .element_count = ARRAY_SIZE(elements),
    .elements = elements,
}
Node composition data.
Definition at line 130 of file main.c.
Referenced by ble_mesh_init().
config_server
esp_ble_mesh_cfg_srv_t config_server static
Initial value:
= {
    .net_transmit = ESP_BLE_MESH_TRANSMIT(2, 20),
    .relay = ESP_BLE_MESH_RELAY_DISABLED,
    .relay_retransmit = ESP_BLE_MESH_TRANSMIT(2, 20),
    .beacon = ESP_BLE_MESH_BEACON_ENABLED,
    .gatt_proxy = ESP_BLE_MESH_GATT_PROXY_NOT_SUPPORTED,
    .friend_state = ESP_BLE_MESH_FRIEND_NOT_SUPPORTED,
    .default_ttl = 7,
}
Configuration Server model state.
Definition at line 88 of file main.c.
dev_uuid
uint8_t dev_uuid[ESP_BLE_MESH_OCTET16_LEN] = { 0x32, 0x10 } static
Definition at line 58 of file main.c.
Referenced by app_main().
elements
esp_ble_mesh_elem_t elements[] static
Initial value:
= {
    ESP_BLE_MESH_ELEMENT(0, root_models, vnd_models),
}
Element list for this composition.
Definition at line 125 of file main.c.
provision
esp_ble_mesh_prov_t provision static
Initial value:
= {
    .uuid = dev_uuid,
}
Provisioning capabilities and identifiers.
Definition at line 137 of file main.c.
Referenced by ble_mesh_init().
pub_timer
esp_timer_handle_t pub_timer static
Definition at line 56 of file main.c.
Referenced by example_ble_mesh_provisioning_cb().
root_models
esp_ble_mesh_model_t root_models[] static
Initial value:
= {
    ESP_BLE_MESH_MODEL_CFG_SRV(&config_server),
}
Root model list for the primary element.
Definition at line 108 of file main.c.
s_vnd_model
esp_ble_mesh_model_t* s_vnd_model static
Definition at line 57 of file main.c.
Referenced by example_ble_mesh_provisioning_cb(), and pub_timer_cb().
vnd_models
esp_ble_mesh_model_t vnd_models[] static
Initial value:
= {
    ESP_BLE_MESH_VENDOR_MODEL(CID_ESP, ESP_BLE_MESH_VND_MODEL_ID_SERVER,
    vnd_op,  &vnd_pub, NULL),
}
Vendor model instances for this node.
Definition at line 119 of file main.c.
Referenced by example_ble_mesh_custom_model_cb(), and example_ble_mesh_provisioning_cb().
vnd_op
esp_ble_mesh_model_op_t vnd_op[] static
Initial value:
= {
    ESP_BLE_MESH_MODEL_OP(ESP_BLE_MESH_VND_MODEL_OP_SEND, 2),
    ESP_BLE_MESH_MODEL_OP_END,
}
Vendor model operation table.
Definition at line 113 of file main.c.