BLE Mesh Multi-Sensor Server: main/sensors/max30101.h File Reference
max30101.h File Reference
MAX30101 heart rate and SpO2 sensor interface.
#include "config.h"
#include "esp_err.h"
#include <stdint.h>
Functions
static esp_err_t max30101_init (void)
Stub initialization when MAX30101 is disabled.
static esp_err_t max30101_start_sampling (void)
Stub sampler start when MAX30101 is disabled.
static uint8_t max30101_get_heart_rate (void)
Stub heart rate getter when MAX30101 is disabled.
static uint8_t max30101_get_spo2 (void)
Stub SpO2 getter when MAX30101 is disabled.
static void max30101_get_raw_values (uint32_t *red, uint32_t *ir)
Stub raw value getter when MAX30101 is disabled.
Detailed Description
MAX30101 heart rate and SpO2 sensor interface.
Definition in file max30101.h.
Function Documentation
max30101_get_heart_rate()
static uint8_t max30101_get_heart_rate (void) inline static
Stub heart rate getter when MAX30101 is disabled.
Definition at line 80 of file max30101.h.
Referenced by pub_timer_cb().
max30101_get_raw_values()
static void max30101_get_raw_values (uint32_t * red, uint32_t * ir) inline static
Stub raw value getter when MAX30101 is disabled.
Definition at line 94 of file max30101.h.
Referenced by pub_timer_cb().
max30101_get_spo2()
static uint8_t max30101_get_spo2 (void) inline static
Stub SpO2 getter when MAX30101 is disabled.
Definition at line 87 of file max30101.h.
Referenced by pub_timer_cb().
max30101_init()
static esp_err_t max30101_init (void) inline static
Stub initialization when MAX30101 is disabled.
Definition at line 66 of file max30101.h.
Referenced by app_main().
max30101_start_sampling()
static esp_err_t max30101_start_sampling (void) inline static
Stub sampler start when MAX30101 is disabled.
Definition at line 73 of file max30101.h.
Referenced by app_main().